extends: "@ciscospark/eslint-config/react"
env:
  jasmine: true
  jest: true
  browser: true
rules:
  require-jsdoc: 0
  # turning off import/no-named-as-default because it breaks our current pattern
  # of exporting the connected version as default and the non-connected version
  # as named.
  import/no-named-as-default: 0
