extends:
- "@ciscospark/eslint-config/es5"
root: true
rules:
  block-spacing: 0
  comma-spacing: 0
  consistent-return: 0
  consistent-this: 0
  default-case: 0
  global-require: 0
  indent: 0
  max-nested-callbacks: 0
  no-else-return: 0
  no-empty-function: 0
  no-extra-bind: 0
  no-extra-parens: 0
  no-invalid-this: 0
  no-multi-spaces: 0
  no-negated-condition: 0
  no-new: 0
  no-plusplus: 0
  no-script-url: 0
  no-shadow: 0
  no-useless-call: 0
  no-void: 0
  no-warning-comments: 0
  operator-linebreak: 0
  radix: 0
  space-infix-ops: 0
  strict: 0
  valid-jsdoc: 0
